In [60]:
import pandas as pd
import numpy as np

In [61]:
df = pd.read_csv("newpivot.csv")

In [62]:
df

,Occupation Code,Occupation Title,Occupation Type,Pivot,Display Level,"Employment Change, 2020-2030","Employment Percent Change, 2020-2030",Occupation Sort,Pivot Values
0,00-0000,"Total, all occupations",Summary,2020 Employment,0,3327.0,16.0,NaN,20856.5
1,00-0000,"Total, all occupations",Summary,2020 Percent of Industry,0,3327.0,16.0,NaN,100.0
2,00-0000,"Total, all occupations",Summary,2020 Percent of Occupation,0,3327.0,16.0,NaN,13.6
3,00-0000,"Total, all occupations",Summary,Projected 2030 Employment,0,3327.0,16.0,NaN,24183.5
4,00-0000,"Total, all occupations",Summary,Projected 2030 Percent of Industry,0,3327.0,16.0,NaN,100.0
...,...,...,...,...,...,...,...,...,...
3871,53-7199,"Material moving workers, all other",Line Item,2020 Percent of Industry,3,0.0,11.5,1048.0,0.0
3872,53-7199,"Material moving workers, all other",Line Item,2020 Percent of Occupation,3,0.0,11.5,1048.0,0.5
3873,53-7199,"Material moving workers, all other",Line Item,Projected 2030 Employment,3,0.0,11.5,1048.0,0.1
3874,53-7199,"Material moving workers, all other",Line Item,Projected 2030 Percent of Industry,3,0.0,11.5,1048.0,0.0
3875,53-7199,"Material moving workers, all other",Line Item,Projected 2030 Percent of Occupation,3,0.0,11.5,1048.0,0.5

<h4>The data from the outlook surveys differs greatly from the OEWS survey. To be able to use this data in Tableau, I used numpy to identify which rows have either "2020" or "2030". Then I used np.where to write a new column in the dataframe<h4>

In [97]:
df['Date'] = np.where(df.Pivot.str.contains("2020"),"2020","2030")     
df

,Occupation Code,Occupation Title,Occupation Type,Pivot,Display Level,"Employment Change, 2020-2030","Employment Percent Change, 2020-2030",Occupation Sort,Pivot Values,t_f,Date
0,00-0000,"Total, all occupations",Summary,2020 Employment,0,3327.0,16.0,NaN,20856.5,False,2020
1,00-0000,"Total, all occupations",Summary,2020 Percent of Industry,0,3327.0,16.0,NaN,100.0,False,2020
2,00-0000,"Total, all occupations",Summary,2020 Percent of Occupation,0,3327.0,16.0,NaN,13.6,False,2020
3,00-0000,"Total, all occupations",Summary,Projected 2030 Employment,0,3327.0,16.0,NaN,24183.5,False,2030
4,00-0000,"Total, all occupations",Summary,Projected 2030 Percent of Industry,0,3327.0,16.0,NaN,100.0,False,2030
...,...,...,...,...,...,...,...,...,...,...,...
3871,53-7199,"Material moving workers, all other",Line Item,2020 Percent of Industry,3,0.0,11.5,1048.0,0.0,False,2020
3872,53-7199,"Material moving workers, all other",Line Item,2020 Percent of Occupation,3,0.0,11.5,1048.0,0.5,False,2020
3873,53-7199,"Material moving workers, all other",Line Item,Projected 2030 Employment,3,0.0,11.5,1048.0,0.1,False,2030
3874,53-7199,"Material moving workers, all other",Line Item,Projected 2030 Percent of Industry,3,0.0,11.5,1048.0,0.0,False,2030
3875,53-7199,"Material moving workers, all other",Line Item,Projected 2030 Percent of Occupation,3,0.0,11.5,1048.0,0.5,False,2030

In [98]:
df.to_csv(r'cleanednewpivot.csv', index = False)